name: Deploy VPC

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: "1.5.7"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v4

      - name: Debug OIDC
        run: |
          echo "Role ARN: ${{ secrets.AWS_ROLE_ARN }}" 
          echo "GITHUB_TOKEN permissions: $(curl -s -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }} | jq .)"

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve

